
package grupo01.ws.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Tue Nov 01 20:20:32 UYT 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "confirmarReservaVenta", namespace = "http://ws.grupo01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "confirmarReservaVenta", namespace = "http://ws.grupo01/")

public class ConfirmarReservaVenta {

    @XmlElement(name = "idReserva")
    private java.lang.String idReserva;

    public java.lang.String getIdReserva() {
        return this.idReserva;
    }

    public void setIdReserva(java.lang.String newIdReserva)  {
        this.idReserva = newIdReserva;
    }

}

