
package grupo01.ws.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Tue Nov 08 20:39:00 UYT 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "consultarEntradasDisponiblesResponse", namespace = "http://impl.ws.grupo01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultarEntradasDisponiblesResponse", namespace = "http://impl.ws.grupo01/")

public class ConsultarEntradasDisponiblesResponse {

    @XmlElement(name = "return")
    private java.util.List<grupo01.database.Horario> _return;

    public java.util.List<grupo01.database.Horario> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<grupo01.database.Horario> new_return)  {
        this._return = new_return;
    }

}

