<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ConfirmarReservaEntradasService" targetNamespace="http://ws.grupo01/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://ws.grupo01/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://ws.grupo01/" schemaLocation="confirmarreservaentradasimpl_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="confirmarReservaVenta">
    <wsdl:part name="parameters" element="tns:confirmarReservaVenta">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="confirmarReservaVentaResponse">
    <wsdl:part name="parameters" element="tns:notificacionConfirmacionReserva">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ConfirmarReservaEntradasImpl">
    <wsdl:operation name="confirmarReservaVenta">
      <wsdl:input name="confirmarReservaVenta" message="tns:confirmarReservaVenta" wsam:Action="urn:ConfirmarReservaVenta">
    </wsdl:input>
      <wsdl:output name="confirmarReservaVentaResponse" message="tns:confirmarReservaVentaResponse" wsam:Action="http://ws.grupo01/CallbackWsImpl/notificacionConfirmacionReserva" wsaw:Action="http://ws.grupo01/CallbackWsImpl/notificacionConfirmacionReserva">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConfirmarReservaEntradasServiceSoapBinding" type="tns:ConfirmarReservaEntradasImpl">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="confirmarReservaVenta">
      <soap:operation soapAction="urn:ConfirmarReservaVenta" style="document"/>
      <wsdl:input name="confirmarReservaVenta">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="confirmarReservaVentaResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ConfirmarReservaEntradasService">
    <wsdl:port name="ConfirmarReservaEntradasPort" binding="tns:ConfirmarReservaEntradasServiceSoapBinding">
      <soap:address location="http://localhost:9090/ConfirmarReservaEntradasPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
