<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="CallbackWsImplService" targetNamespace="http://ws.grupo01/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://ws.grupo01/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://ws.grupo01/" schemaLocation="callbackwsimpl_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="notificacionConfirmacionReservaResponse">
    <wsdl:part name="parameters" element="tns:notificacionConfirmacionReservaResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="notificacionConfirmacionReserva">
    <wsdl:part name="parameters" element="tns:notificacionConfirmacionReserva">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="CallbackWsImpl">
    <wsdl:operation name="notificacionConfirmacionReserva">
      <wsdl:input name="notificacionConfirmacionReserva" message="tns:notificacionConfirmacionReserva">
    </wsdl:input>
      <wsdl:output name="notificacionConfirmacionReservaResponse" message="tns:notificacionConfirmacionReservaResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CallbackWsImplServiceSoapBinding" type="tns:CallbackWsImpl">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="notificacionConfirmacionReserva">
      <soap:operation soapAction="urn:notificacionConfirmacionReserva" style="document"/>
      <wsdl:input name="notificacionConfirmacionReserva">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="notificacionConfirmacionReservaResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CallbackWsImplService">
    <wsdl:port name="CallbackWsImplPort" binding="tns:CallbackWsImplServiceSoapBinding">
      <soap:address location="http://localhost:9090/CallbackWsImplPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
