
package grupo01.ws.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Sat Nov 05 18:32:25 GMT-03:00 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "confirmarReservaVentaResponse", namespace = "http://ws.grupo01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "confirmarReservaVentaResponse", namespace = "http://ws.grupo01/")

public class ConfirmarReservaVentaResponse {


}

