
package grupo01.ws.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Fri Nov 11 22:24:47 GMT-03:00 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "notificacionConfirmacionReservaResponse", namespace = "http://ws.grupo01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "notificacionConfirmacionReservaResponse", namespace = "http://ws.grupo01/")

public class NotificacionConfirmacionReservaResponse {


}

