
package grupo01.ws.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Fri Oct 28 00:00:19 GMT-03:00 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "reservarEntradasResponse", namespace = "http://impl.ws.grupo01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reservarEntradasResponse", namespace = "http://impl.ws.grupo01/")

public class ReservarEntradasResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

