
package grupo01.ws.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Fri Oct 28 00:00:19 GMT-03:00 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "reservarEntradas", namespace = "http://impl.ws.grupo01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reservarEntradas", namespace = "http://impl.ws.grupo01/")

public class ReservarEntradas {

    @XmlElement(name = "espetaculo")
    private java.lang.String espetaculo;

    public java.lang.String getEspetaculo() {
        return this.espetaculo;
    }

    public void setEspetaculo(java.lang.String newEspetaculo)  {
        this.espetaculo = newEspetaculo;
    }

}

