
package grupo01.ws.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Sun Nov 13 20:49:43 GMT-03:00 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "anularVentaEntrada", namespace = "http://ws.grupo01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "anularVentaEntrada", namespace = "http://ws.grupo01/", propOrder = {"idCoonfirmacion", "idMedioPago"})

public class AnularVentaEntrada {

    @XmlElement(name = "idCoonfirmacion")
    private java.lang.Long idCoonfirmacion;
    @XmlElement(name = "idMedioPago")
    private java.lang.Long idMedioPago;

    public java.lang.Long getIdCoonfirmacion() {
        return this.idCoonfirmacion;
    }

    public void setIdCoonfirmacion(java.lang.Long newIdCoonfirmacion)  {
        this.idCoonfirmacion = newIdCoonfirmacion;
    }

    public java.lang.Long getIdMedioPago() {
        return this.idMedioPago;
    }

    public void setIdMedioPago(java.lang.Long newIdMedioPago)  {
        this.idMedioPago = newIdMedioPago;
    }

}

