
package grupo01.ws.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Sun Nov 13 20:49:43 GMT-03:00 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "anularVentaEntradaResponse", namespace = "http://ws.grupo01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "anularVentaEntradaResponse", namespace = "http://ws.grupo01/")

public class AnularVentaEntradaResponse {

    @XmlElement(name = "idAnulacion")
    private java.lang.Long idAnulacion;

    public java.lang.Long getIdAnulacion() {
        return this.idAnulacion;
    }

    public void setIdAnulacion(java.lang.Long newIdAnulacion)  {
        this.idAnulacion = newIdAnulacion;
    }

}

