
package grupo01.ws.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Fri Nov 11 20:54:45 GMT-03:00 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "notificacionConfirmacionReserva", namespace = "http://ws.grupo01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "notificacionConfirmacionReserva", namespace = "http://ws.grupo01/")

public class ConfirmarReservaVentaResponse {

    @XmlElement(name = "notificacionConfirmacionReserva")
    private java.lang.Long notificacionConfirmacionReserva;

    public java.lang.Long getNotificacionConfirmacionReserva() {
        return this.notificacionConfirmacionReserva;
    }

    public void setNotificacionConfirmacionReserva(java.lang.Long newNotificacionConfirmacionReserva)  {
        this.notificacionConfirmacionReserva = newNotificacionConfirmacionReserva;
    }

}

