
package grupo01.ws.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Sun Nov 13 21:21:26 GMT-03:00 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "notificacionConfirmacionReserva", namespace = "http://ws.grupo01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "notificacionConfirmacionReserva", namespace = "http://ws.grupo01/")

public class ConfirmarReservaVentaResponse {

    @XmlElement(name = "entrada")
    private grupo01.ws.data.EntradaData entrada;

    public grupo01.ws.data.EntradaData getEntrada() {
        return this.entrada;
    }

    public void setEntrada(grupo01.ws.data.EntradaData newEntrada)  {
        this.entrada = newEntrada;
    }

}

