
package grupo01.ws.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Tue Nov 08 23:42:35 UYT 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "consultarEntradasDisponibles", namespace = "http://impl.ws.grupo01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultarEntradasDisponibles", namespace = "http://impl.ws.grupo01/", propOrder = {"idEvento", "fecha"})

public class ConsultarEntradasDisponibles {

    @XmlElement(name = "idEvento")
    private java.lang.Integer idEvento;
    @XmlElement(name = "fecha")
    private java.util.Date fecha;

    public java.lang.Integer getIdEvento() {
        return this.idEvento;
    }

    public void setIdEvento(java.lang.Integer newIdEvento)  {
        this.idEvento = newIdEvento;
    }

    public java.util.Date getFecha() {
        return this.fecha;
    }

    public void setFecha(java.util.Date newFecha)  {
        this.fecha = newFecha;
    }

}

