
package grupo01.ws.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Fri Nov 11 19:58:07 GMT-03:00 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "consultarEstadoReservaResponse", namespace = "http://impl.ws.grupo01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultarEstadoReservaResponse", namespace = "http://impl.ws.grupo01/")

public class ConsultarEstadoReservaResponse {

    @XmlElement(name = "estadoReserva")
    private java.lang.Integer estadoReserva;

    public java.lang.Integer getEstadoReserva() {
        return this.estadoReserva;
    }

    public void setEstadoReserva(java.lang.Integer newEstadoReserva)  {
        this.estadoReserva = newEstadoReserva;
    }

}

