
package grupo01.ws.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Tue Nov 08 23:42:35 UYT 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "consultarEntradasDisponiblesResponse", namespace = "http://impl.ws.grupo01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultarEntradasDisponiblesResponse", namespace = "http://impl.ws.grupo01/")

public class ConsultarEntradasDisponiblesResponse {

    @XmlElement(name = "Horarios")
    private java.util.List<grupo01.ws.data.HorarioData> Horarios;

    public java.util.List<grupo01.ws.data.HorarioData> getHorarios() {
        return this.Horarios;
    }

    public void setHorarios(java.util.List<grupo01.ws.data.HorarioData> newHorarios)  {
        this.Horarios = newHorarios;
    }

}

