
package grupo01.ws.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Tue Nov 01 20:21:16 UYT 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "consultarEstadoReservaResponse", namespace = "http://impl.ws.grupo01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultarEstadoReservaResponse", namespace = "http://impl.ws.grupo01/")

public class ConsultarEstadoReservaResponse {


}

