
package grupo01.ws.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Wed Nov 09 23:46:08 GMT-03:00 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "reservarEntradas", namespace = "http://impl.ws.grupo01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reservarEntradas", namespace = "http://impl.ws.grupo01/", propOrder = {"idEvento", "fecha", "horarios"})

public class ReservarEntradas {

    @XmlElement(name = "idEvento")
    private java.lang.Integer idEvento;
    @XmlElement(name = "fecha")
    private java.util.Date fecha;
    @XmlElement(name = "horarios")
    private java.util.List<grupo01.ws.data.HorarioData> horarios;

    public java.lang.Integer getIdEvento() {
        return this.idEvento;
    }

    public void setIdEvento(java.lang.Integer newIdEvento)  {
        this.idEvento = newIdEvento;
    }

    public java.util.Date getFecha() {
        return this.fecha;
    }

    public void setFecha(java.util.Date newFecha)  {
        this.fecha = newFecha;
    }

    public java.util.List<grupo01.ws.data.HorarioData> getHorarios() {
        return this.horarios;
    }

    public void setHorarios(java.util.List<grupo01.ws.data.HorarioData> newHorarios)  {
        this.horarios = newHorarios;
    }

}

