
package grupo01.ws.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Tue Nov 01 20:13:23 UYT 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "reservarEntradas", namespace = "http://impl.ws.grupo01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reservarEntradas", namespace = "http://impl.ws.grupo01/")

public class ReservarEntradas {

    @XmlElement(name = "espectaculo")
    private java.lang.String espectaculo;

    public java.lang.String getEspectaculo() {
        return this.espectaculo;
    }

    public void setEspectaculo(java.lang.String newEspectaculo)  {
        this.espectaculo = newEspectaculo;
    }

}

