
package grupo01.ws.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Wed Nov 09 23:46:08 GMT-03:00 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "reservarEntradasResponse", namespace = "http://impl.ws.grupo01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reservarEntradasResponse", namespace = "http://impl.ws.grupo01/")

public class ReservarEntradasResponse {

    @XmlElement(name = "idReserva")
    private java.lang.Long idReserva;

    public java.lang.Long getIdReserva() {
        return this.idReserva;
    }

    public void setIdReserva(java.lang.Long newIdReserva)  {
        this.idReserva = newIdReserva;
    }

}

