
package backoffice.redstrawberry.wsclient;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServicioRedStrawberry", targetNamespace = "http://services.grupo01.middleware/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServicioRedStrawberry {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Oneway
    public void recibirOC(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
