
package backoffice.redstrawberry.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioRedStrawberryService", targetNamespace = "http://services.grupo01.middleware/", wsdlLocation = "http://172.16.143.109:8080/RedStrawberry/ServicioRedStrawberry?wsdl")
public class ServicioRedStrawberryService
    extends Service
{

    private final static URL SERVICIOREDSTRAWBERRYSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOREDSTRAWBERRYSERVICE_EXCEPTION;
    private final static QName SERVICIOREDSTRAWBERRYSERVICE_QNAME = new QName("http://services.grupo01.middleware/", "ServicioRedStrawberryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("http://172.16.143.109:8080/RedStrawberry/ServicioRedStrawberry?wsdl");
        	url = new URL("https://172.16.143.109:8443/RedStrawberry/ServicioRedStrawberry?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOREDSTRAWBERRYSERVICE_WSDL_LOCATION = url;
        SERVICIOREDSTRAWBERRYSERVICE_EXCEPTION = e;
    }

    public ServicioRedStrawberryService() {
        super(__getWsdlLocation(), SERVICIOREDSTRAWBERRYSERVICE_QNAME);
    }

    public ServicioRedStrawberryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOREDSTRAWBERRYSERVICE_QNAME, features);
    }

    public ServicioRedStrawberryService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOREDSTRAWBERRYSERVICE_QNAME);
    }

    public ServicioRedStrawberryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOREDSTRAWBERRYSERVICE_QNAME, features);
    }

    public ServicioRedStrawberryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioRedStrawberryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServicioRedStrawberry
     */
    @WebEndpoint(name = "ServicioRedStrawberryPort")
    public IServicioRedStrawberry getServicioRedStrawberryPort() {
        return super.getPort(new QName("http://services.grupo01.middleware/", "ServicioRedStrawberryPort"), IServicioRedStrawberry.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServicioRedStrawberry
     */
    @WebEndpoint(name = "ServicioRedStrawberryPort")
    public IServicioRedStrawberry getServicioRedStrawberryPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.grupo01.middleware/", "ServicioRedStrawberryPort"), IServicioRedStrawberry.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOREDSTRAWBERRYSERVICE_EXCEPTION!= null) {
            throw SERVICIOREDSTRAWBERRYSERVICE_EXCEPTION;
        }
        return SERVICIOREDSTRAWBERRYSERVICE_WSDL_LOCATION;
    }

}
